In [1]:
import pandas as pd 
placement_df = pd.read_csv(r"C:\Users\rohit\Documents\CareerInsight AI Student Placement Prediction & Analytics Platform\data\raw\Indian_Student_Placement_Dataset_2025.csv")

In [2]:
salary_df = pd.read_csv(r"C:\Users\rohit\Documents\CareerInsight AI Student Placement Prediction & Analytics Platform\data\raw\ai_job_salary_dataset_10k.csv")

In [3]:
skill_df = pd.read_csv(r"C:\Users\rohit\Documents\CareerInsight AI Student Placement Prediction & Analytics Platform\data\raw\DMA DATASET.csv")

In [4]:
placement_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   student_id            12000 non-null  int64
 1   gender                12000 non-null  object
 2   age                   12000 non-null  int64
 3   degree                12000 non-null  object
 4   branch                12000 non-null  object
 5   cgpa                  12000 non-null  float64
 6   backlogs              12000 non-null  int64
 7   internships           12000 non-null  int64
 8   certifications        12000 non-null  int64
 9   coding_skills         12000 non-null  int64
 10  communication_skills  12000 non-null  int64
 11  aptitude_score        12000 non-null  int64
 12  projects              12000 non-null  int64
 13  placed                12000 non-null  int64
 14  company_type          3652 non-null   object
 15  package_lpa           12000 non-null  float64
dtypes: float64(2), int64(10), object(4)
memory usage: 1.5+ MB

In [5]:
placement_df.isnull().sum()

student_id                 0
gender                     0
age                        0
degree                     0
branch                     0
cgpa                       0
backlogs                   0
internships                0
certifications             0
coding_skills              0
communication_skills       0
aptitude_score             0
projects                   0
placed                     0
company_type            8348
package_lpa                0
dtype: int64

In [6]:
placement_df.describe()

,student_id,age,cgpa,backlogs,internships,certifications,coding_skills,communication_skills,aptitude_score,projects,placed,package_lpa
count,12000.00000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000
mean,6000.50000,21.988333,7.645308,1.491583,1.501167,2.509000,5.495333,5.500583,69.327833,2.504750,0.304333,2.741692
std,3464.24595,1.422158,1.243433,1.118347,1.123582,1.709092,2.889724,2.888459,17.338207,1.699133,0.460144,4.568126
min,1.00000,20.000000,5.500000,0.000000,0.000000,0.000000,1.000000,1.000000,40.000000,0.000000,0.000000,0.000000
25%,3000.75000,21.000000,6.560000,0.000000,0.000000,1.000000,3.000000,3.000000,54.000000,1.000000,0.000000,0.000000
50%,6000.50000,22.000000,7.645000,1.000000,1.000000,3.000000,5.000000,6.000000,69.000000,3.000000,0.000000,0.000000
75%,9000.25000,23.000000,8.720000,2.000000,3.000000,4.000000,8.000000,8.000000,84.000000,4.000000,1.000000,5.170000
max,12000.00000,24.000000,9.800000,3.000000,3.000000,5.000000,10.000000,10.000000,99.000000,5.000000,1.000000,15.000000

In [7]:
placement_df.describe(include="object")

       gender degree      branch company_type
count   12000  12000       12000         3652
unique      2      4           6            3
top      Male    BCA  Mechanical      Product
freq     6008   3071        2107         1252

In [8]:
missing_values = placement_df.isnull().sum()
missing_values = missing_values[missing_values > 0]

print(missing_values)

company_type    8348
dtype: int64

In [9]:
missing_percentage = (placement_df.isnull().sum() / len(placement_df)) * 100

missing_report = pd.DataFrame({
    "Missing Values": placement_df.isnull().sum(),
    "Percentage": missing_percentage
})

missing_report = missing_report[missing_report["Missing Values"] > 0]

missing_report

              Missing Values  Percentage
company_type            8348   69.566667

In [10]:
placement_df.duplicated().sum()

np.int64(0)

In [11]:
placement_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   student_id            12000 non-null  int64
 1   gender                12000 non-null  object
 2   age                   12000 non-null  int64
 3   degree                12000 non-null  object
 4   branch                12000 non-null  object
 5   cgpa                  12000 non-null  float64
 6   backlogs              12000 non-null  int64
 7   internships           12000 non-null  int64
 8   certifications        12000 non-null  int64
 9   coding_skills         12000 non-null  int64
 10  communication_skills  12000 non-null  int64
 11  aptitude_score        12000 non-null  int64
 12  projects              12000 non-null  int64
 13  placed                12000 non-null  int64
 14  company_type          3652 non-null   object
 15  package_lpa           12000 non-null  float64
dtypes: float64(2), int64(10), object(4)
memory usage: 1.5+ MB

In [12]:
placement_df["placed"].value_counts()

placed
0    8348
1    3652
Name: count, dtype: int64

In [13]:
placement_df["placed"].value_counts(normalize=True) * 100

placed
0    69.566667
1    30.433333
Name: proportion, dtype: float64